version: "3"
services:
  rabbit:
    image: rabbitmq:3.7-management
    hostname: node-2.uggla.fr
    container_name: rabbit
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "35197:35197"
    environment:
      - "RABBITMQ_USE_LONGNAME=true"
      - "RABBITMQ_LOGS=/var/log/rabbitmq/log/rabbit.log"
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./logs:/var/log/rabbitmq
